import type { MythEra, MythTheme, Story } from "./types";

type StorySeed = [
  id: string,
  titleZh: string,
  titleEn: string,
  country: string,
  countryEn: string,
  region: string,
  lat: number,
  lng: number,
  theme: MythTheme,
  era: MythEra,
  icon: string
];

const seeds: StorySeed[] = [
  ["cn-mulan", "花木兰", "Mulan", "中国", "China", "东亚", 35.2, 113.8, "hero", "classical", "🪖"],
  ["cn-white-snake", "白蛇传", "Legend of the White Snake", "中国", "China", "东亚", 30.3, 120.1, "love", "medieval", "🐍"],
  ["cn-meng-jiangnu", "孟姜女哭长城", "Meng Jiangnu", "中国", "China", "东亚", 40.4, 116.0, "love", "classical", "🧱"],
  ["cn-cowherd-weaver", "牛郎织女", "Cowherd and Weaver Girl", "中国", "China", "东亚", 36.7, 117.0, "love", "ancient", "🌌"],
  ["cn-jingwei", "精卫填海", "Jingwei Fills the Sea", "中国", "China", "东亚", 39.0, 121.6, "flood", "ancient", "🐦"],
  ["cn-kuafu", "夸父逐日", "Kuafu Chases the Sun", "中国", "China", "东亚", 34.6, 110.9, "sun", "ancient", "🏃"],
  ["cn-pangu", "盘古开天", "Pangu Separates Sky and Earth", "中国", "China", "东亚", 30.9, 112.2, "creation", "ancient", "🪓"],
  ["cn-yu-flood", "大禹治水", "Yu Tames the Flood", "中国", "China", "东亚", 34.8, 113.6, "flood", "ancient", "🌊"],
  ["tw-mazu", "妈祖护海", "Mazu Protects the Sea", "中国台湾", "Taiwan", "东亚", 25.0, 121.5, "flood", "medieval", "⛵"],
  ["jp-momotaro", "桃太郎", "Momotaro", "日本", "Japan", "东亚", 34.7, 133.9, "hero", "medieval", "🍑"],
  ["jp-kaguya", "辉夜姬", "Princess Kaguya", "日本", "Japan", "东亚", 35.4, 138.7, "moon", "classical", "🎋"],
  ["jp-urashima", "浦岛太郎", "Urashima Taro", "日本", "Japan", "东亚", 35.0, 135.8, "underworld", "classical", "🐢"],
  ["jp-tengu", "天狗", "Tengu", "日本", "Japan", "东亚", 36.2, 138.2, "hero", "medieval", "👺"],
  ["jp-kappa", "河童", "Kappa", "日本", "Japan", "东亚", 35.9, 139.6, "flood", "medieval", "🥒"],
  ["kr-hong-gildong", "洪吉童", "Hong Gildong", "韩国", "Korea", "东亚", 35.8, 127.1, "hero", "medieval", "🥷"],
  ["kr-jumong", "朱蒙传说", "Jumong", "韩国", "Korea", "东亚", 40.0, 125.4, "hero", "ancient", "🏹"],
  ["mn-alan-goa", "阿兰豁阿", "Alan Goa", "蒙古", "Mongolia", "内亚", 47.1, 102.8, "creation", "medieval", "✨"],
  ["kz-korkyt", "库尔库特", "Korkyt Ata", "哈萨克斯坦", "Kazakhstan", "内亚", 44.8, 65.5, "underworld", "medieval", "🎻"],
  ["uz-alpamysh", "阿勒帕米什", "Alpamysh", "乌兹别克斯坦", "Uzbekistan", "中亚", 41.3, 69.2, "hero", "medieval", "🐎"],
  ["in-savitri", "莎维德丽救夫", "Savitri and Satyavan", "印度", "India", "南亚", 21.1, 79.1, "love", "ancient", "🪷"],
  ["in-ramayana", "罗摩与悉多", "Rama and Sita", "印度", "India", "南亚", 26.8, 82.2, "hero", "ancient", "🏹"],
  ["in-krishna", "黑天降蛇", "Krishna Subdues Kaliya", "印度", "India", "南亚", 27.5, 77.7, "dragon", "ancient", "🪈"],
  ["in-samudra-manthan", "搅乳海", "Churning of the Ocean", "印度", "India", "南亚", 20.6, 78.9, "creation", "ancient", "🌊"],
  ["pk-sohni-mahiwal", "索妮与马希瓦尔", "Sohni Mahiwal", "巴基斯坦", "Pakistan", "南亚", 30.2, 71.5, "love", "medieval", "🏺"],
  ["np-kumari", "活女神库玛丽", "Kumari", "尼泊尔", "Nepal", "喜马拉雅", 27.7, 85.3, "hero", "modern", "👑"],
  ["bt-druk", "雷龙德鲁克", "Druk the Thunder Dragon", "不丹", "Bhutan", "喜马拉雅", 27.5, 90.4, "dragon", "medieval", "🐉"],
  ["lk-kuveni", "库维尼", "Kuveni", "斯里兰卡", "Sri Lanka", "南亚", 7.9, 80.7, "love", "ancient", "🌿"],
  ["mm-thuwanna", "苏瓦纳山传说", "Thuwanna Mountain Tale", "缅甸", "Myanmar", "东南亚", 21.9, 96.1, "hero", "classical", "⛰️"],
  ["th-nang-nak", "娜娜鬼妻", "Nang Nak", "泰国", "Thailand", "东南亚", 13.7, 100.8, "love", "modern", "🕯️"],
  ["th-himmapan", "喜马潘森林", "Himmapan Forest", "泰国", "Thailand", "东南亚", 15.0, 101.0, "creation", "classical", "🌳"],
  ["kh-reamker", "柬埔寨罗摩传奇", "Reamker", "柬埔寨", "Cambodia", "东南亚", 13.4, 103.9, "hero", "classical", "🐒"],
  ["la-phra-lak", "帕拉帕兰", "Phra Lak Phra Lam", "老挝", "Laos", "东南亚", 17.9, 102.6, "hero", "classical", "🌾"],
  ["vn-thanh-giong", "圣董天王", "Thanh Giong", "越南", "Vietnam", "东南亚", 21.1, 105.9, "hero", "ancient", "🎋"],
  ["vn-banh-chung", "粽饼传说", "Banh Chung Tale", "越南", "Vietnam", "东南亚", 20.8, 106.0, "creation", "ancient", "🍃"],
  ["id-nyai-roro-kidul", "南海女王", "Nyai Roro Kidul", "印度尼西亚", "Indonesia", "东南亚", -8.0, 110.4, "flood", "classical", "🌊"],
  ["id-malin-kundang", "马林昆当", "Malin Kundang", "印度尼西亚", "Indonesia", "东南亚", -0.9, 100.4, "underworld", "classical", "🪨"],
  ["my-mahsuri", "玛苏丽", "Mahsuri", "马来西亚", "Malaysia", "东南亚", 6.3, 99.8, "love", "modern", "🩸"],
  ["sg-sang-nila", "狮城王子", "Sang Nila Utama", "新加坡", "Singapore", "东南亚", 1.3, 103.8, "hero", "medieval", "🦁"],
  ["ph-ibalon", "伊巴隆史诗", "Ibalon", "菲律宾", "Philippines", "东南亚", 13.6, 123.2, "hero", "classical", "⚔️"],
  ["ph-bakunawa", "巴库纳瓦吞月", "Bakunawa", "菲律宾", "Philippines", "东南亚", 10.3, 123.9, "dragon", "ancient", "🌑"],
  ["gr-orpheus", "俄耳甫斯下冥界", "Orpheus in the Underworld", "希腊", "Greece", "地中海", 40.6, 22.9, "underworld", "classical", "🎵"],
  ["gr-icarus", "伊卡洛斯", "Icarus", "希腊", "Greece", "地中海", 35.2, 25.1, "sun", "classical", "🪽"],
  ["gr-medusa", "美杜莎", "Medusa", "希腊", "Greece", "地中海", 37.4, 22.8, "hero", "classical", "🐍"],
  ["gr-odyssey", "奥德修斯归乡", "Odysseus Returns Home", "希腊", "Greece", "地中海", 38.4, 20.7, "hero", "classical", "⛵"],
  ["it-romulus", "罗慕路斯与雷穆斯", "Romulus and Remus", "意大利", "Italy", "欧洲", 41.9, 12.5, "creation", "ancient", "🐺"],
  ["it-befana", "贝法娜女巫", "Befana", "意大利", "Italy", "欧洲", 43.1, 12.4, "hero", "modern", "🧹"],
  ["fr-bluebeard", "蓝胡子", "Bluebeard", "法国", "France", "西欧", 48.9, 2.3, "underworld", "modern", "🔑"],
  ["fr-beauty-beast", "美女与野兽", "Beauty and the Beast", "法国", "France", "西欧", 47.2, 2.4, "love", "modern", "🌹"],
  ["de-hansel-gretel", "糖果屋", "Hansel and Gretel", "德国", "Germany", "中欧", 51.0, 10.4, "underworld", "modern", "🍬"],
  ["de-snow-white", "白雪公主", "Snow White", "德国", "Germany", "中欧", 50.6, 9.0, "love", "modern", "🍎"],
  ["de-rapunzel", "长发公主", "Rapunzel", "德国", "Germany", "中欧", 51.5, 9.9, "love", "modern", "🪜"],
  ["dk-little-mermaid", "小美人鱼", "The Little Mermaid", "丹麦", "Denmark", "北欧", 55.7, 12.6, "love", "modern", "🧜"],
  ["dk-snow-queen", "冰雪女王", "The Snow Queen", "丹麦", "Denmark", "北欧", 55.4, 10.4, "underworld", "modern", "❄️"],
  ["se-nils", "尼尔斯骑鹅旅行", "Nils Holgersson", "瑞典", "Sweden", "北欧", 58.4, 15.6, "hero", "modern", "🪿"],
  ["no-trolls", "挪威巨怪", "Norwegian Trolls", "挪威", "Norway", "北欧", 61.0, 8.0, "underworld", "medieval", "🪨"],
  ["is-yule-lads", "圣诞小伙", "Yule Lads", "冰岛", "Iceland", "北欧", 64.1, -21.9, "hero", "modern", "🎁"],
  ["ie-cu-chulainn", "库丘林", "Cu Chulainn", "爱尔兰", "Ireland", "西欧", 54.1, -6.4, "hero", "medieval", "🛡️"],
  ["ie-banshee", "报丧女妖", "Banshee", "爱尔兰", "Ireland", "西欧", 53.4, -8.0, "underworld", "medieval", "🌫️"],
  ["gb-robin-hood", "罗宾汉", "Robin Hood", "英国", "United Kingdom", "欧洲", 53.2, -1.1, "hero", "medieval", "🏹"],
  ["gb-beowulf", "贝奥武夫", "Beowulf", "英国", "United Kingdom", "欧洲", 52.6, -0.4, "dragon", "medieval", "🐲"],
  ["es-don-juan", "唐璜", "Don Juan", "西班牙", "Spain", "南欧", 37.4, -5.9, "love", "modern", "🎭"],
  ["pt-sebastian", "塞巴斯蒂昂归来", "King Sebastian's Return", "葡萄牙", "Portugal", "南欧", 38.7, -9.1, "hero", "modern", "👑"],
  ["ru-baba-yaga", "芭芭雅嘎", "Baba Yaga", "俄罗斯", "Russia", "东欧", 56.0, 38.0, "underworld", "medieval", "🛖"],
  ["ru-koschei", "不死的科谢伊", "Koschei the Deathless", "俄罗斯", "Russia", "东欧", 55.0, 40.0, "underworld", "medieval", "🥚"],
  ["pl-wawel-dragon", "瓦维尔龙", "Wawel Dragon", "波兰", "Poland", "中欧", 50.1, 19.9, "dragon", "medieval", "🐉"],
  ["cz-golem", "布拉格魔像", "Golem of Prague", "捷克", "Czechia", "中欧", 50.1, 14.4, "creation", "medieval", "🧱"],
  ["ro-baba-dochia", "多基亚婆婆", "Baba Dochia", "罗马尼亚", "Romania", "东欧", 45.9, 24.9, "moon", "medieval", "🧥"],
  ["rs-vila", "维拉仙女", "Vila", "塞尔维亚", "Serbia", "东欧", 44.8, 20.5, "love", "medieval", "🧚"],
  ["eg-isis", "伊西斯寻夫", "Isis Searches for Osiris", "埃及", "Egypt", "北非", 29.9, 31.1, "love", "ancient", "🪷"],
  ["eg-horus-set", "荷鲁斯与赛特", "Horus and Set", "埃及", "Egypt", "北非", 26.8, 31.8, "hero", "ancient", "🦅"],
  ["ma-issa", "艾莎与海", "Aisha of the Sea", "摩洛哥", "Morocco", "北非", 33.6, -7.6, "flood", "modern", "🌊"],
  ["tn-carthage-dido", "狄多女王", "Queen Dido", "突尼斯", "Tunisia", "北非", 36.9, 10.3, "love", "ancient", "🔥"],
  ["ml-sundiata", "松迪亚塔", "Sundiata", "马里", "Mali", "西非", 12.6, -8.0, "hero", "medieval", "🦁"],
  ["sn-leuk", "兔子莱克", "Leuk the Hare", "塞内加尔", "Senegal", "西非", 14.7, -17.4, "hero", "classical", "🐇"],
  ["ng-tortoise", "乌龟智者", "Tortoise the Trickster", "尼日利亚", "Nigeria", "西非", 6.5, 3.4, "hero", "classical", "🐢"],
  ["cm-jengu", "水灵延古", "Jengu", "喀麦隆", "Cameroon", "中非", 4.0, 9.7, "flood", "classical", "🧜"],
  ["cd-mokele", "姆克雷姆贝贝", "Mokele-mbembe", "刚果", "Congo", "中非", -1.4, 15.5, "dragon", "modern", "🦕"],
  ["tz-kibo-mawenzi", "乞力马扎罗兄弟峰", "Kibo and Mawenzi", "坦桑尼亚", "Tanzania", "东非", -3.1, 37.4, "creation", "classical", "🏔️"],
  ["mg-iboniamasiboniamanoro", "伊博尼亚", "Ibonia", "马达加斯加", "Madagascar", "印度洋", -18.9, 47.5, "hero", "classical", "🌿"],
  ["au-bunyip", "本耶普", "Bunyip", "澳大利亚", "Australia", "大洋洲", -35.3, 149.1, "flood", "modern", "🦫"],
  ["au-tiddalik", "喝光水的青蛙", "Tiddalik", "澳大利亚", "Australia", "大洋洲", -25.0, 134.0, "flood", "ancient", "🐸"],
  ["nz-maui-fish", "毛伊钓起北岛", "Maui Fishes Up the North Island", "新西兰", "New Zealand", "大洋洲", -38.0, 176.0, "creation", "ancient", "🎣"],
  ["fj-dakuwaqa", "鲨神达库瓦卡", "Dakuwaqa", "斐济", "Fiji", "太平洋", -18.1, 178.4, "flood", "ancient", "🦈"],
  ["ws-sina-eel", "西娜与鳗鱼", "Sina and the Eel", "萨摩亚", "Samoa", "太平洋", -13.8, -171.8, "love", "ancient", "🥥"],
  ["to-maui-islands", "毛伊创造群岛", "Maui Creates Islands", "汤加", "Tonga", "太平洋", -21.2, -175.2, "creation", "ancient", "🪝"],
  ["us-paul-bunyan", "保罗班扬", "Paul Bunyan", "美国", "United States", "北美洲", 46.8, -92.1, "hero", "modern", "🪓"],
  ["us-john-henry", "约翰亨利", "John Henry", "美国", "United States", "北美洲", 37.8, -81.2, "hero", "modern", "🔨"],
  ["us-sleepy-hollow", "断头谷", "Sleepy Hollow", "美国", "United States", "北美洲", 41.1, -73.9, "underworld", "modern", "🎃"],
  ["us-wendigo", "温迪戈", "Wendigo", "美国", "United States", "北美洲", 47.7, -92.0, "underworld", "modern", "🌲"],
  ["ca-sedna", "海女神塞德娜", "Sedna", "加拿大", "Canada", "北美洲", 64.0, -95.0, "flood", "ancient", "🦭"],
  ["ca-nanabozho", "纳纳布佐", "Nanabozho", "加拿大", "Canada", "北美洲", 49.9, -97.1, "hero", "ancient", "🐇"],
  ["mx-la-llorona", "哭泣女人", "La Llorona", "墨西哥", "Mexico", "中美洲", 19.4, -99.1, "underworld", "modern", "💧"],
  ["mx-popocatepetl", "波波卡特佩特与伊斯塔", "Popocatepetl and Iztaccihuatl", "墨西哥", "Mexico", "中美洲", 19.0, -98.6, "love", "ancient", "🌋"],
  ["gt-cadejo", "卡德霍", "Cadejo", "危地马拉", "Guatemala", "中美洲", 14.6, -90.5, "underworld", "modern", "🐕"],
  ["cu-guije", "古伊赫水怪", "Guije", "古巴", "Cuba", "加勒比", 22.0, -79.5, "flood", "modern", "🌿"],
  ["ht-zombi", "僵身传说", "Zombie Folklore", "海地", "Haiti", "加勒比", 18.5, -72.3, "underworld", "modern", "🕯️"],
  ["co-el-dorado", "黄金国", "El Dorado", "哥伦比亚", "Colombia", "南美洲", 4.7, -74.1, "hero", "modern", "🏆"],
  ["ve-maria-lionza", "玛丽亚莱昂萨", "Maria Lionza", "委内瑞拉", "Venezuela", "南美洲", 10.2, -68.7, "love", "modern", "🦋"],
  ["ec-cantuña", "坎图尼亚", "Cantuña", "厄瓜多尔", "Ecuador", "南美洲", -0.2, -78.5, "hero", "modern", "⛪"],
  ["bo-ekeko", "埃克科", "Ekeko", "玻利维亚", "Bolivia", "南美洲", -16.5, -68.1, "creation", "modern", "🎒"],
  ["cl-trauco", "特劳科", "Trauco", "智利", "Chile", "南美洲", -42.5, -73.8, "love", "modern", "🌲"],
  ["cl-caleuche", "幽灵船卡勒乌切", "Caleuche", "智利", "Chile", "南美洲", -42.0, -74.0, "flood", "modern", "🚢"],
  ["py-pombero", "蓬贝罗", "Pombero", "巴拉圭", "Paraguay", "南美洲", -25.3, -57.6, "underworld", "modern", "🎒"],
  ["uy-luz-mala", "恶光", "Luz Mala", "乌拉圭", "Uruguay", "南美洲", -34.9, -56.2, "underworld", "modern", "💡"]
];

const themeDescriptions: Record<MythTheme, string> = {
  sun: "太阳、光明和天体秩序",
  flood: "水域、河流、海洋和灾变记忆",
  fire: "火种、文明技术和净化力量",
  dragon: "龙蛇、巨兽和自然威力",
  love: "爱情、承诺、禁忌和分离",
  moon: "月亮、夜晚、周期和思念",
  underworld: "冥界、禁忌、亡灵和未知边界",
  hero: "英雄试炼、远行和共同体守护",
  creation: "创世、起源、地景和族群记忆"
};

const themeImages: Record<MythTheme, string> = {
  sun: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500&auto=format&fit=crop",
  flood: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&auto=format&fit=crop",
  fire: "https://images.unsplash.com/photo-1518562180175-34a163b1a9a6?w=500&auto=format&fit=crop",
  dragon: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&auto=format&fit=crop",
  love: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=500&auto=format&fit=crop",
  moon: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=500&auto=format&fit=crop",
  underworld: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=500&auto=format&fit=crop",
  hero: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500&auto=format&fit=crop",
  creation: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=500&auto=format&fit=crop"
};

export const generatedStories: Story[] = seeds.map((seed, index) => {
  const [id, titleZh, titleEn, country, countryEn, region, lat, lng, theme, era, icon] = seed;
  const relatedStoryIds = seeds
    .filter((candidate) => candidate[0] !== id && candidate[8] === theme)
    .slice(index % 5, (index % 5) + 3)
    .map((candidate) => candidate[0]);

  return {
    id,
    titleZh,
    titleEn,
    country,
    countryEn,
    region,
    lat,
    lng,
    theme,
    era,
    icon,
    imageUrl: themeImages[theme],
    summaryZh: `${titleZh}是${country}流传的神话、民间传说或经典童话母题，围绕${themeDescriptions[theme]}展开。它适合放在世界地图上与其他文明的相似故事对照观看，也适合后续扩写成完整音频故事。`,
    summaryEn: `${titleEn} is a myth, folk tale, or classic tale from ${countryEn}, centered on ${themeDescriptions[theme]}. It is useful for comparing similar motifs across cultures and can be expanded into a full narrated story.`,
    relatedStoryIds
  };
});
