import type { MythEra, MythTheme, Story } from "./types";

type Seed = [
  id: string,
  titleZh: string,
  titleEn: string,
  country: string,
  countryEn: string,
  region: string,
  lat: number,
  lng: number,
  theme: MythTheme,
  era: MythEra,
  icon: string
];

const seeds: Seed[] = [
  ["cn-lotus-lamp", "宝莲灯", "The Lotus Lantern", "中国", "China", "东亚", 34.5, 109.0, "hero", "medieval", "🏮"],
  ["cn-ne-zha", "哪吒闹海", "Nezha Conquers the Sea", "中国", "China", "东亚", 39.0, 117.7, "hero", "classical", "🪷"],
  ["cn-jiang-ziya", "姜子牙封神", "Jiang Ziya Invests the Gods", "中国", "China", "东亚", 35.0, 114.0, "creation", "classical", "🎣"],
  ["cn-monkey-king", "孙悟空大闹天宫", "Monkey King in Heaven", "中国", "China", "东亚", 31.0, 104.0, "hero", "classical", "🐒"],
  ["cn-red-boy", "红孩儿", "Red Boy", "中国", "China", "东亚", 30.0, 106.0, "fire", "classical", "🔥"],
  ["cn-lady-meng-po", "孟婆汤", "Meng Po's Soup", "中国", "China", "东亚", 29.5, 111.8, "underworld", "classical", "🍵"],
  ["cn-eight-immortals", "八仙过海", "Eight Immortals Cross the Sea", "中国", "China", "东亚", 37.9, 120.7, "flood", "classical", "🌊"],
  ["cn-lu-dongbin", "吕洞宾", "Lu Dongbin", "中国", "China", "东亚", 36.0, 112.0, "hero", "classical", "⚔️"],
  ["cn-xiwangmu", "西王母", "Queen Mother of the West", "中国", "China", "东亚", 36.5, 94.8, "creation", "ancient", "🍑"],
  ["cn-yan-huang", "炎黄传说", "Yan and Huang", "中国", "China", "东亚", 35.6, 110.0, "creation", "ancient", "🛖"],
  ["cn-cangjie", "仓颉造字", "Cangjie Creates Writing", "中国", "China", "东亚", 34.6, 109.5, "creation", "ancient", "✍️"],
  ["cn-shennong", "神农尝百草", "Shennong Tastes Herbs", "中国", "China", "东亚", 30.6, 111.0, "hero", "ancient", "🌿"],
  ["cn-fuxi", "伏羲画卦", "Fuxi Draws the Trigrams", "中国", "China", "东亚", 34.7, 105.6, "creation", "ancient", "☯️"],
  ["cn-leigong", "雷公电母", "Thunder Duke and Lightning Mother", "中国", "China", "东亚", 28.2, 113.0, "fire", "ancient", "⚡"],
  ["cn-yue-lao", "月老红线", "Yue Lao's Red Thread", "中国", "China", "东亚", 34.3, 108.9, "love", "classical", "🧵"],
  ["cn-liang-zhu", "梁山伯与祝英台", "Butterfly Lovers", "中国", "China", "东亚", 30.0, 120.6, "love", "classical", "🦋"],
  ["jp-tanuki", "狸猫变形", "Tanuki Shapeshifter", "日本", "Japan", "东亚", 36.5, 137.0, "hero", "medieval", "🦝"],
  ["jp-kitsune", "狐嫁女", "Fox Bride", "日本", "Japan", "东亚", 35.0, 136.0, "love", "medieval", "🦊"],
  ["jp-yuki-onna", "雪女", "Yuki-onna", "日本", "Japan", "东亚", 39.7, 140.1, "underworld", "modern", "❄️"],
  ["jp-issun-boshi", "一寸法师", "Issun-boshi", "日本", "Japan", "东亚", 34.9, 135.7, "hero", "medieval", "🥢"],
  ["jp-shuten-doji", "酒吞童子", "Shuten-doji", "日本", "Japan", "东亚", 35.3, 135.1, "hero", "medieval", "🍶"],
  ["jp-hachikazuki", "钵冠公主", "Hachikazuki", "日本", "Japan", "东亚", 34.7, 135.5, "love", "medieval", "👒"],
  ["jp-crane-wife", "鹤妻", "Crane Wife", "日本", "Japan", "东亚", 37.6, 139.0, "love", "classical", "🪶"],
  ["kr-sim-cheong", "沈清传", "Sim Cheong", "韩国", "Korea", "东亚", 35.1, 126.8, "love", "medieval", "🌊"],
  ["kr-chunhyang", "春香传", "Chunhyangjeon", "韩国", "Korea", "东亚", 35.4, 127.4, "love", "medieval", "🌸"],
  ["kr-heungbu", "兴夫传", "Heungbu and Nolbu", "韩国", "Korea", "东亚", 35.8, 128.0, "hero", "medieval", "🐦"],
  ["kr-gumiho", "九尾狐", "Gumiho", "韩国", "Korea", "东亚", 37.4, 127.8, "underworld", "modern", "🦊"],
  ["mn-ergene-kun", "额尔古纳昆", "Ergene Kun", "蒙古", "Mongolia", "内亚", 49.0, 107.0, "creation", "medieval", "⛰️"],
  ["mn-khori-tumed", "天鹅少女", "Swan Maiden", "蒙古", "Mongolia", "内亚", 48.4, 100.2, "love", "medieval", "🦢"],
  ["tr-dede-korkut", "德德科尔库特", "Dede Korkut", "土耳其", "Turkey", "西亚", 39.9, 32.8, "hero", "medieval", "📜"],
  ["tr-nasreddin", "纳斯雷丁", "Nasreddin Hodja", "土耳其", "Turkey", "西亚", 39.7, 31.6, "hero", "medieval", "🫏"],
  ["ir-simurgh", "神鸟西穆尔格", "Simurgh", "伊朗", "Iran", "西亚", 36.3, 59.6, "creation", "medieval", "🦚"],
  ["ir-rustam", "鲁斯塔姆", "Rostam", "伊朗", "Iran", "西亚", 30.3, 57.1, "hero", "medieval", "🛡️"],
  ["ir-bijan-manijeh", "比詹与玛尼杰", "Bijan and Manijeh", "伊朗", "Iran", "西亚", 34.0, 47.0, "love", "medieval", "❤️"],
  ["iq-etana", "埃塔纳乘鹰", "Etana and the Eagle", "伊拉克", "Iraq", "美索不达米亚", 33.1, 44.0, "hero", "ancient", "🦅"],
  ["iq-adapa", "阿达帕", "Adapa", "伊拉克", "Iraq", "美索不达米亚", 31.3, 45.6, "creation", "ancient", "🍞"],
  ["sy-adonis", "阿多尼斯", "Adonis", "叙利亚", "Syria", "西亚", 34.0, 36.0, "love", "ancient", "🌺"],
  ["il-samson", "参孙", "Samson", "以色列", "Israel", "西亚", 31.5, 34.9, "hero", "ancient", "🦁"],
  ["il-jonah", "约拿与大鱼", "Jonah and the Great Fish", "以色列", "Israel", "西亚", 32.0, 34.8, "flood", "ancient", "🐋"],
  ["sa-antarah", "安塔拉", "Antarah", "沙特阿拉伯", "Saudi Arabia", "西亚", 24.7, 46.7, "hero", "medieval", "🐎"],
  ["ye-queen-bilqis", "比勒吉斯女王", "Queen Bilqis", "也门", "Yemen", "西亚", 15.4, 44.2, "hero", "ancient", "👑"],
  ["in-nala-damayanti", "那罗与达摩衍蒂", "Nala and Damayanti", "印度", "India", "南亚", 23.2, 77.4, "love", "ancient", "🦢"],
  ["in-hanuman", "哈奴曼跃海", "Hanuman Leaps the Sea", "印度", "India", "南亚", 9.3, 79.3, "hero", "ancient", "🐒"],
  ["in-garuda-amrita", "迦楼罗夺甘露", "Garuda Steals Amrita", "印度", "India", "南亚", 16.5, 80.6, "hero", "ancient", "🦅"],
  ["in-markandeya", "摩根德耶", "Markandeya", "印度", "India", "南亚", 12.9, 79.1, "underworld", "ancient", "🕉️"],
  ["in-matsya", "鱼化身救洪水", "Matsya Saves the World", "印度", "India", "南亚", 22.6, 88.4, "flood", "ancient", "🐟"],
  ["bd-bonbibi", "森林女神邦比比", "Bonbibi", "孟加拉国", "Bangladesh", "南亚", 22.0, 89.5, "hero", "modern", "🌳"],
  ["np-manjushri", "文殊开谷", "Manjushri Opens the Valley", "尼泊尔", "Nepal", "喜马拉雅", 27.7, 85.3, "creation", "classical", "⚔️"],
  ["th-sang-thong", "金螺王子", "Sang Thong", "泰国", "Thailand", "东南亚", 14.3, 100.6, "hero", "classical", "🐚"],
  ["th-kinnari", "紧那罗", "Kinnari", "泰国", "Thailand", "东南亚", 15.5, 101.0, "love", "classical", "🪽"],
  ["kh-neang-kongrey", "孔瑞公主", "Neang Kong Rey", "柬埔寨", "Cambodia", "东南亚", 12.6, 104.9, "love", "classical", "👸"],
  ["la-naga-mekong", "湄公河纳迦", "Mekong Naga", "老挝", "Laos", "东南亚", 17.9, 102.7, "dragon", "classical", "🐍"],
  ["vn-tam-cam", "金云翘式灰姑娘", "Tam Cam", "越南", "Vietnam", "东南亚", 20.7, 105.7, "love", "classical", "👠"],
  ["vn-lieu-hanh", "柳杏公主", "Princess Lieu Hanh", "越南", "Vietnam", "东南亚", 20.4, 106.2, "hero", "classical", "🌸"],
  ["id-sangkuriang", "桑库里昂", "Sangkuriang", "印度尼西亚", "Indonesia", "东南亚", -6.9, 107.6, "creation", "classical", "⛰️"],
  ["id-timun-mas", "金黄瓜女孩", "Timun Mas", "印度尼西亚", "Indonesia", "东南亚", -7.6, 110.8, "hero", "classical", "🥒"],
  ["id-calonarang", "卡洛纳朗", "Calon Arang", "印度尼西亚", "Indonesia", "东南亚", -8.5, 115.3, "underworld", "classical", "🕯️"],
  ["my-puteri-gunung-ledang", "金山公主", "Princess of Mount Ledang", "马来西亚", "Malaysia", "东南亚", 2.4, 102.6, "love", "classical", "⛰️"],
  ["my-bujang-senang", "巨鳄传说", "Bujang Senang", "马来西亚", "Malaysia", "东南亚", 1.6, 110.3, "dragon", "modern", "🐊"],
  ["ph-lam-ang", "兰昂史诗", "Biag ni Lam-ang", "菲律宾", "Philippines", "东南亚", 17.4, 120.5, "hero", "classical", "🐓"],
  ["ph-mayon", "马荣火山", "Mayon Volcano Legend", "菲律宾", "Philippines", "东南亚", 13.3, 123.7, "love", "classical", "🌋"],
  ["gr-theseus", "忒修斯与迷宫", "Theseus and the Minotaur", "希腊", "Greece", "地中海", 35.3, 25.1, "hero", "classical", "🧶"],
  ["gr-jason", "伊阿宋与金羊毛", "Jason and the Golden Fleece", "希腊", "Greece", "地中海", 39.0, 22.0, "hero", "classical", "🐏"],
  ["gr-atalanta", "阿塔兰忒", "Atalanta", "希腊", "Greece", "地中海", 38.0, 22.0, "hero", "classical", "🏃"],
  ["gr-pandora", "潘多拉", "Pandora", "希腊", "Greece", "地中海", 37.8, 23.8, "creation", "classical", "📦"],
  ["gr-europa", "欧罗巴", "Europa", "希腊", "Greece", "地中海", 35.4, 24.8, "love", "classical", "🐂"],
  ["gr-cassandra", "卡珊德拉", "Cassandra", "希腊", "Greece", "地中海", 39.9, 26.2, "underworld", "classical", "🔮"],
  ["it-odysseus-polyphemus", "独眼巨人", "Polyphemus", "意大利", "Italy", "地中海", 37.5, 14.0, "hero", "classical", "👁️"],
  ["it-cola-pesce", "鱼人科拉", "Cola Pesce", "意大利", "Italy", "欧洲", 38.2, 15.6, "flood", "medieval", "🐟"],
  ["it-taranta", "塔兰塔舞", "Tarantella Legend", "意大利", "Italy", "欧洲", 40.6, 17.2, "underworld", "modern", "🕷️"],
  ["fr-cinderella", "灰姑娘", "Cinderella", "法国", "France", "西欧", 48.0, 2.2, "love", "modern", "👠"],
  ["fr-puss-boots", "穿靴子的猫", "Puss in Boots", "法国", "France", "西欧", 47.0, 2.8, "hero", "modern", "🐈"],
  ["fr-sleeping-beauty", "睡美人", "Sleeping Beauty", "法国", "France", "西欧", 47.8, 1.9, "love", "modern", "🌹"],
  ["fr-red-riding", "小红帽", "Little Red Riding Hood", "法国", "France", "西欧", 46.8, 3.0, "underworld", "modern", "🧺"],
  ["de-rumpelstiltskin", "侏儒怪", "Rumpelstiltskin", "德国", "Germany", "中欧", 51.4, 10.2, "creation", "modern", "🧵"],
  ["de-bremen", "不来梅乐队", "Town Musicians of Bremen", "德国", "Germany", "中欧", 53.1, 8.8, "hero", "modern", "🎺"],
  ["de-frog-prince", "青蛙王子", "Frog Prince", "德国", "Germany", "中欧", 50.9, 9.4, "love", "modern", "🐸"],
  ["de-six-swans", "六只天鹅", "Six Swans", "德国", "Germany", "中欧", 52.0, 11.0, "love", "modern", "🦢"],
  ["nl-flying-dutchman", "飞翔的荷兰人", "Flying Dutchman", "荷兰", "Netherlands", "西欧", 52.3, 4.8, "flood", "modern", "⛵"],
  ["be-swan-knight", "天鹅骑士", "Swan Knight", "比利时", "Belgium", "西欧", 50.8, 4.4, "hero", "medieval", "🦢"],
  ["ch-william-tell", "威廉退尔", "William Tell", "瑞士", "Switzerland", "中欧", 46.9, 8.3, "hero", "medieval", "🏹"],
  ["at-krampus", "坎卜斯", "Krampus", "奥地利", "Austria", "中欧", 47.8, 13.0, "underworld", "modern", "🔔"],
  ["cz-libuse", "莉布谢预言", "Libuse", "捷克", "Czechia", "中欧", 50.1, 14.4, "creation", "medieval", "👑"],
  ["pl-pan-twardowski", "特瓦尔多夫斯基", "Pan Twardowski", "波兰", "Poland", "中欧", 52.2, 21.0, "underworld", "medieval", "🌙"],
  ["hu-white-stag", "白鹿传说", "White Stag", "匈牙利", "Hungary", "中欧", 47.5, 19.0, "creation", "medieval", "🦌"],
  ["ro-master-manole", "马诺莱大师", "Master Manole", "罗马尼亚", "Romania", "东欧", 45.0, 24.0, "creation", "medieval", "🏛️"],
  ["bg-samodiva", "萨莫迪瓦", "Samodiva", "保加利亚", "Bulgaria", "东欧", 42.7, 25.5, "love", "medieval", "🧚"],
  ["gr-basilisk", "巴西利斯克", "Basilisk", "希腊", "Greece", "地中海", 40.0, 21.0, "dragon", "medieval", "🦎"],
  ["se-tomte", "农场小精灵", "Tomte", "瑞典", "Sweden", "北欧", 59.3, 18.1, "hero", "modern", "🧣"],
  ["fi-vainamoinen", "维纳莫宁", "Vainamoinen", "芬兰", "Finland", "北欧", 61.5, 25.0, "hero", "medieval", "🎶"],
  ["no-huldra", "胡尔德拉", "Huldra", "挪威", "Norway", "北欧", 60.4, 7.2, "love", "medieval", "🌲"],
  ["is-saga-grettir", "格雷蒂尔", "Grettir", "冰岛", "Iceland", "北欧", 65.0, -19.0, "hero", "medieval", "🪓"],
  ["gb-gawain-green", "高文与绿骑士", "Gawain and the Green Knight", "英国", "United Kingdom", "欧洲", 53.0, -2.0, "hero", "medieval", "🟢"],
  ["gb-lady-godiva", "戈黛娃夫人", "Lady Godiva", "英国", "United Kingdom", "欧洲", 52.4, -1.5, "hero", "medieval", "🐎"],
  ["gb-black-shuck", "黑犬", "Black Shuck", "英国", "United Kingdom", "欧洲", 52.6, 1.3, "underworld", "medieval", "🐕"],
  ["ie-deirdre", "黛尔德丽", "Deirdre of the Sorrows", "爱尔兰", "Ireland", "西欧", 54.6, -6.7, "love", "medieval", "💔"],
  ["ie-children-lir", "李尔王之子", "Children of Lir", "爱尔兰", "Ireland", "西欧", 53.7, -8.9, "love", "medieval", "🦢"],
  ["es-la-mano-negra", "黑手传说", "La Mano Negra", "西班牙", "Spain", "南欧", 40.0, -4.0, "underworld", "modern", "✋"],
  ["es-bernat-pescaire", "伯纳特渔夫", "Bernat the Fisher", "西班牙", "Spain", "南欧", 41.4, 2.2, "flood", "medieval", "🎣"],
  ["pt-moura-encantada", "被施咒的摩尔少女", "Moura Encantada", "葡萄牙", "Portugal", "南欧", 39.0, -8.0, "love", "medieval", "💎"],
  ["ru-vasilisa", "瓦西丽莎", "Vasilisa the Beautiful", "俄罗斯", "Russia", "东欧", 56.3, 44.0, "hero", "medieval", "🕯️"],
  ["ru-snegurochka", "雪姑娘", "Snegurochka", "俄罗斯", "Russia", "东欧", 57.8, 40.9, "love", "modern", "❄️"],
  ["ua-kyiv-founders", "基辅三兄妹", "Founders of Kyiv", "乌克兰", "Ukraine", "东欧", 50.5, 30.5, "creation", "medieval", "🏙️"],
  ["lt-egle", "蛇王后埃格蕾", "Egle the Queen of Serpents", "立陶宛", "Lithuania", "东欧", 55.2, 23.9, "love", "medieval", "🐍"],
  ["lv-kurbads", "库尔巴兹", "Kurbads", "拉脱维亚", "Latvia", "东欧", 56.9, 24.1, "hero", "medieval", "⚔️"],
  ["ee-kalevipoeg", "卡列维波埃格", "Kalevipoeg", "爱沙尼亚", "Estonia", "东欧", 58.7, 25.0, "hero", "medieval", "🪨"],
  ["eg-bastet", "猫神巴斯泰特", "Bastet", "埃及", "Egypt", "北非", 30.6, 31.5, "hero", "ancient", "🐈"],
  ["eg-sekhmet", "塞赫迈特", "Sekhmet", "埃及", "Egypt", "北非", 25.7, 32.6, "sun", "ancient", "🦁"],
  ["eg-thoth", "托特", "Thoth", "埃及", "Egypt", "北非", 27.8, 30.8, "moon", "ancient", "🪶"],
  ["dz-anzar", "雨神安扎尔", "Anzar", "阿尔及利亚", "Algeria", "北非", 36.7, 4.0, "flood", "ancient", "🌧️"],
  ["ma-lalla-mira", "拉拉米拉", "Lalla Mira", "摩洛哥", "Morocco", "北非", 31.0, -8.0, "love", "modern", "🌹"],
  ["ly-gorgon", "戈耳工海岸", "Gorgon Coast", "利比亚", "Libya", "北非", 32.0, 20.0, "underworld", "classical", "🐍"],
  ["et-abuna-yemata", "岩壁圣人", "Abuna Yemata", "埃塞俄比亚", "Ethiopia", "东非", 14.1, 39.4, "hero", "medieval", "⛰️"],
  ["sd-kandake", "坎达克女王", "Kandake", "苏丹", "Sudan", "东北非", 16.9, 33.7, "hero", "ancient", "👑"],
  ["ug-walumbe", "瓦伦贝", "Walumbe", "乌干达", "Uganda", "东非", 0.4, 32.5, "underworld", "ancient", "💀"],
  ["rw-nyabingi", "尼亚宾吉", "Nyabingi", "卢旺达", "Rwanda", "东非", -1.9, 30.1, "hero", "modern", "🥁"],
  ["ke-murungu", "穆伦古", "Murungu", "肯尼亚", "Kenya", "东非", -0.1, 37.0, "creation", "ancient", "☁️"],
  ["tz-hare-hyena", "野兔与鬣狗", "Hare and Hyena", "坦桑尼亚", "Tanzania", "东非", -6.8, 39.2, "hero", "classical", "🐇"],
  ["so-dhegdheer", "长耳女妖", "Dhegdheer", "索马里", "Somalia", "东非", 2.0, 45.3, "underworld", "modern", "👂"],
  ["ng-moremi", "莫雷米", "Moremi Ajasoro", "尼日利亚", "Nigeria", "西非", 7.5, 4.6, "hero", "medieval", "🛡️"],
  ["ng-sango", "雷神尚戈", "Sango", "尼日利亚", "Nigeria", "西非", 8.0, 4.0, "fire", "ancient", "⚡"],
  ["gh-nyame", "天神尼亚美", "Nyame", "加纳", "Ghana", "西非", 6.7, -1.6, "creation", "ancient", "☁️"],
  ["ci-queen-abla", "阿布拉波库女王", "Queen Abla Pokou", "科特迪瓦", "Cote d'Ivoire", "西非", 7.7, -5.0, "hero", "modern", "👑"],
  ["bj-mami-wata", "水灵玛米瓦塔", "Mami Wata", "贝宁", "Benin", "西非", 6.5, 2.6, "flood", "modern", "🧜"],
  ["za-tokoloshe", "托科洛希", "Tokoloshe", "南非", "South Africa", "南部非洲", -29.0, 25.0, "underworld", "modern", "🧌"],
  ["zw-nyaminyami", "赞比西河神", "Nyaminyami", "津巴布韦", "Zimbabwe", "南部非洲", -17.8, 25.8, "dragon", "modern", "🐍"],
  ["bw-mantis", "螳螂造物者", "Mantis Creator", "博茨瓦纳", "Botswana", "南部非洲", -22.0, 24.0, "creation", "ancient", "🦗"],
  ["au-seven-sisters", "七姐妹", "Seven Sisters", "澳大利亚", "Australia", "大洋洲", -25.3, 131.0, "moon", "ancient", "✨"],
  ["au-three-brothers", "三兄弟山", "Three Brothers", "澳大利亚", "Australia", "大洋洲", -31.7, 152.8, "creation", "ancient", "⛰️"],
  ["au-mimis", "米米精灵", "Mimi Spirits", "澳大利亚", "Australia", "大洋洲", -12.5, 133.0, "hero", "ancient", "🎨"],
  ["nz-hine-nui-te-po", "夜之女神", "Hine-nui-te-po", "新西兰", "New Zealand", "大洋洲", -39.0, 175.0, "underworld", "ancient", "🌑"],
  ["nz-tawhaki", "塔法基登天", "Tawhaki", "新西兰", "New Zealand", "大洋洲", -37.8, 176.0, "hero", "ancient", "⚡"],
  ["haw-pele", "火山女神佩蕾", "Pele", "夏威夷", "Hawaii", "太平洋", 19.4, -155.3, "fire", "ancient", "🌋"],
  ["haw-hina", "月女神希娜", "Hina", "夏威夷", "Hawaii", "太平洋", 20.8, -156.3, "moon", "ancient", "🌙"],
  ["fj-degei", "德盖蛇神", "Degei", "斐济", "Fiji", "太平洋", -17.8, 178.0, "creation", "ancient", "🐍"],
  ["pg-asaro", "泥人传说", "Asaro Mudmen", "巴布亚新几内亚", "Papua New Guinea", "大洋洲", -6.1, 145.4, "hero", "modern", "🎭"],
  ["us-pecos-bill", "佩科斯比尔", "Pecos Bill", "美国", "United States", "北美洲", 31.4, -103.5, "hero", "modern", "🤠"],
  ["us-casey-jones", "凯西琼斯", "Casey Jones", "美国", "United States", "北美洲", 35.6, -88.8, "hero", "modern", "🚂"],
  ["us-brer-rabbit", "兔子布雷尔", "Br'er Rabbit", "美国", "United States", "北美洲", 33.7, -84.4, "hero", "modern", "🐇"],
  ["us-mothman", "蛾人", "Mothman", "美国", "United States", "北美洲", 38.8, -82.1, "underworld", "modern", "🦋"],
  ["us-jackalope", "鹿角兔", "Jackalope", "美国", "United States", "北美洲", 43.1, -107.6, "hero", "modern", "🦌"],
  ["ca-ogopogo", "奥戈波戈", "Ogopogo", "加拿大", "Canada", "北美洲", 49.9, -119.5, "dragon", "modern", "🐉"],
  ["ca-sasquatch", "大脚野人", "Sasquatch", "加拿大", "Canada", "北美洲", 53.7, -122.7, "underworld", "modern", "👣"],
  ["gl-qivittoq", "山野流浪者", "Qivittoq", "格陵兰", "Greenland", "北美洲", 64.2, -51.7, "underworld", "modern", "❄️"],
  ["mx-cipactli", "大地鳄怪", "Cipactli", "墨西哥", "Mexico", "中美洲", 19.6, -99.0, "creation", "ancient", "🐊"],
  ["mx-xolotl", "索洛托尔", "Xolotl", "墨西哥", "Mexico", "中美洲", 19.4, -99.2, "underworld", "ancient", "🐕"],
  ["gt-xocomil", "阿蒂特兰风", "Xocomil", "危地马拉", "Guatemala", "中美洲", 14.7, -91.2, "love", "modern", "🌬️"],
  ["bz-tata-duende", "塔塔杜恩德", "Tata Duende", "伯利兹", "Belize", "中美洲", 17.2, -88.8, "hero", "modern", "🎩"],
  ["pa-tule", "图勒故事", "Tule Tales", "巴拿马", "Panama", "中美洲", 8.5, -80.0, "creation", "ancient", "🪶"],
  ["jm-rolling-calf", "滚犊鬼", "Rolling Calf", "牙买加", "Jamaica", "加勒比", 18.1, -77.3, "underworld", "modern", "🐂"],
  ["tt-soucouyant", "苏库扬", "Soucouyant", "特立尼达和多巴哥", "Trinidad and Tobago", "加勒比", 10.7, -61.2, "fire", "modern", "🔥"],
  ["co-madre-monte", "山林母亲", "Madre Monte", "哥伦比亚", "Colombia", "南美洲", 5.0, -75.0, "flood", "modern", "🌿"],
  ["co-patasola", "独脚女", "Patasola", "哥伦比亚", "Colombia", "南美洲", 4.5, -74.0, "underworld", "modern", "🦶"],
  ["pe-viracocha", "维拉科查", "Viracocha", "秘鲁", "Peru", "南美洲", -13.5, -72.0, "creation", "ancient", "🌊"],
  ["pe-ayar-brothers", "阿亚尔兄弟", "Ayar Brothers", "秘鲁", "Peru", "南美洲", -13.3, -72.2, "creation", "ancient", "⛰️"],
  ["bo-tunupa", "图努帕", "Tunupa", "玻利维亚", "Bolivia", "南美洲", -19.9, -67.6, "creation", "ancient", "🌋"],
  ["br-saci", "萨西", "Saci", "巴西", "Brazil", "南美洲", -15.8, -47.9, "hero", "modern", "🧢"],
  ["br-boitata", "火蛇博伊塔塔", "Boitata", "巴西", "Brazil", "南美洲", -25.4, -49.3, "fire", "modern", "🐍"],
  ["br-curupira", "库鲁皮拉", "Curupira", "巴西", "Brazil", "南美洲", -3.5, -62.0, "hero", "modern", "👣"],
  ["ar-ceibo", "赛波花", "Ceibo Flower", "阿根廷", "Argentina", "南美洲", -31.4, -60.0, "love", "modern", "🌺"],
  ["ar-nahuelito", "纳韦利托", "Nahuelito", "阿根廷", "Argentina", "南美洲", -41.1, -71.3, "dragon", "modern", "🐉"],
  ["cl-pincoya", "海女平科亚", "Pincoya", "智利", "Chile", "南美洲", -42.6, -73.8, "flood", "modern", "🧜"],
  ["cl-alicanto", "金翼鸟", "Alicanto", "智利", "Chile", "南美洲", -24.0, -69.0, "hero", "modern", "🪽"],
  ["uy-yerba-mate", "马黛茶传说", "Yerba Mate Legend", "乌拉圭", "Uruguay", "南美洲", -32.5, -56.0, "creation", "modern", "🍵"],
  ["py-jasyrendy", "火虫传说", "Jasy Jatere", "巴拉圭", "Paraguay", "南美洲", -25.3, -57.6, "moon", "modern", "🌙"]
];

const images: Record<MythTheme, string> = {
  sun: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500&auto=format&fit=crop",
  flood: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&auto=format&fit=crop",
  fire: "https://images.unsplash.com/photo-1518562180175-34a163b1a9a6?w=500&auto=format&fit=crop",
  dragon: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=500&auto=format&fit=crop",
  love: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=500&auto=format&fit=crop",
  moon: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=500&auto=format&fit=crop",
  underworld: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=500&auto=format&fit=crop",
  hero: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500&auto=format&fit=crop",
  creation: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=500&auto=format&fit=crop"
};

const themeZh: Record<MythTheme, string> = {
  sun: "太阳与光明",
  flood: "河海与洪水",
  fire: "火焰与文明",
  dragon: "龙蛇与巨兽",
  love: "爱情与誓约",
  moon: "月亮与夜空",
  underworld: "冥界与禁忌",
  hero: "英雄与试炼",
  creation: "创世与起源"
};

export const moreGeneratedStories: Story[] = seeds.map((seed, index) => {
  const [id, titleZh, titleEn, country, countryEn, region, lat, lng, theme, era, icon] = seed;
  const relatedStoryIds = seeds
    .filter((candidate) => candidate[0] !== id && candidate[8] === theme)
    .slice(index % 7, (index % 7) + 3)
    .map((candidate) => candidate[0]);

  return {
    id,
    titleZh,
    titleEn,
    country,
    countryEn,
    region,
    lat,
    lng,
    theme,
    era,
    icon,
    imageUrl: images[theme],
    summaryZh: `${titleZh}是${country}流传的神话、童话、民间故事或史诗片段，核心母题是${themeZh[theme]}。它被放入地图后，可以和其他地区相似题材互相连线，帮助用户看到不同文明之间反复出现的想象结构。`,
    summaryEn: `${titleEn} is a myth, fairy tale, folk legend, or epic motif from ${countryEn}. Its core theme is ${theme}, making it useful for comparing recurring story patterns across cultures.`,
    relatedStoryIds
  };
});
